; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

; Base configuration for build tools.
[base_build]
build_flags =
  -Wall -Wextra

; Base configuration for Atmel AVR based Arduino boards.
[base_atmelavr]
platform = atmelavr
framework = arduino
monitor_speed = 57600
test_ignore = desktop/*
lib_deps =
  Wire
  SPI
  adafruit/Adafruit BNO055
  adafruit/Adafruit BusIO
  adafruit/Adafruit Unified Sensor

; Base configuration for Espressif ESP32 based boards.
[base_espressif32]
platform = espressif32
framework = arduino
monitor_speed = 57600
test_ignore = desktop/*
lib_deps =
  Wire
  SPI
  adafruit/Adafruit BNO055
  adafruit/Adafruit BusIO
  adafruit/Adafruit Unified Sensor

; Base configuration for Raspberry Pi RP2040 based boards.
[base_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower
monitor_speed = 57600
monitor_port = /dev/ttyACM*
test_ignore = desktop/*
build_flags =
  -DARDUINO_ARCH_RP2040
board_build.filesystem_size = 0m
board_build.f_cpu = 200000000L
lib_deps =
  Wire
  SPI
  adafruit/Adafruit BNO055
  adafruit/Adafruit BusIO
  adafruit/Adafruit Unified Sensor
lib_ignore =
  Adafruit TinyUSB Library
build_src_filter =
  +<*>
  -<*esp32*>
board_build.arduino.earlephilhower.usb_manufacturer = Ekumen
board_build.arduino.earlephilhower.usb_product = Andino Firmware 2024 - RP2040

; Base configuration for desktop platforms (for unit testing).
[base_desktop]
platform = native
test_framework = googletest
test_build_src = true
build_src_filter =
  +<encoder.cpp>
  +<motor.cpp>
  +<pid.cpp>
  +<shell.cpp>

; Environment for Arduino Uno.
[env:uno]
extends = base_build, base_atmelavr
board = uno

; Environment for Arduino Nano.
[env:nanoatmega328]
extends = base_build, base_atmelavr
board = nanoatmega328

; Environment for desktop platforms (Windows, macOS, Linux, etc).
[env:desktop]
extends = base_build, base_desktop

; Environment for ESP32 DevKit boards.
[env:esp32dev]
extends = base_build, base_espressif32
board = esp32dev

; Environment for Raspberry Pi Pico boards.
[env:pico]
extends = base_build, base_rp2040
board = pico
